# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_istat', models.CharField(max_length=10)),
                ('codice_catastale', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=100)),
                ('nome_de', models.CharField(blank=True, max_length=100, null=True)),
                ('cap', models.CharField(blank=True, max_length=10, null=True)),
                ('capoluogo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Comune',
                'verbose_name_plural': 'Comuni',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(db_index=True, max_length=5, unique=True)),
                ('sigla', models.CharField(max_length=5)),
                ('nome', models.CharField(max_length=50)),
                ('nome_de', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Province',
            },
        ),
        migrations.CreateModel(
            name='Regione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(db_index=True, max_length=5, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('nome_de', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Regione',
                'verbose_name_plural': 'Regioni',
            },
        ),
        migrations.CreateModel(
            name='RipartizioneGeografica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(db_index=True, max_length=5, unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Ripartizione',
                'verbose_name_plural': 'Ripartizioni',
            },
        ),
        migrations.AddField(
            model_name='provincia',
            name='regione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comuni.Regione'),
        ),
        migrations.AddField(
            model_name='comune',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comuni.Provincia'),
        ),
        migrations.AddField(
            model_name='comune',
            name='ripartizione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comuni.RipartizioneGeografica'),
        ),
        migrations.AlterModelOptions(
            name='comune',
            options={'ordering': ('nome',), 'verbose_name': 'Comune', 'verbose_name_plural': 'Comuni'},
        ),
        migrations.AlterModelOptions(
            name='provincia',
            options={'ordering': ('nome',), 'verbose_name': 'Provincia', 'verbose_name_plural': 'Province'},
        ),
        migrations.AlterModelOptions(
            name='regione',
            options={'ordering': ('nome',), 'verbose_name': 'Regione', 'verbose_name_plural': 'Regioni'},
        ),
        migrations.AlterModelOptions(
            name='ripartizionegeografica',
            options={'ordering': ('nome',), 'verbose_name': 'Ripartizione', 'verbose_name_plural': 'Ripartizioni'},
        ),
        migrations.AlterField(
            model_name='comune',
            name='nome',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='nome',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='regione',
            name='nome',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ripartizionegeografica',
            name='nome',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
